before_commands:
    - 'composer install'
tools:
    php_code_coverage:
        test_command: phpunit -c phpunit.xml.dist
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR1